### ISSUE TITLE
Cannot find open Tab by two first letters

### ISSUE THREAD

**Issue by kmorcinek** [chrisseroka/chrome-omnicomplete#1]
I have a page in other tab https://blog.gutek.pl/

When I type "j" i can see (correct):
![image](https://user-images.githubusercontent.com/1745689/34726341-003cbdb4-f554-11e7-877b-c719b637a9b4.png)

and when I type "jg" list is empty (not correct):
![image](https://user-images.githubusercontent.com/1745689/34726401-307b288a-f554-11e7-9abb-aad445d93d5e.png)

Bug or feature ? ;)

**Comment by chrisseroka** [comment]
Bug, but it's already fixed ! Please update version from Chrome Web Store.

2018-01-09 15:46 GMT+01:00 Krzysztof Morcinek <notifications@github.com>:

**Comment by kmorcinek** [comment]
Tested and works, thx.
