### ISSUE TITLE
The way how the bookmarks are sorted could be improved.

### ISSUE THREAD

**Issue by zbigniew-klasik** [chrisseroka/chrome-omnicomplete#2]
This is a very nice tool. I love it but I think that the search results sorting could be better. My problem is that I have a lot of bookmarks and one of them has a very simple name "maps". When I search for "maps" then I expect this bookmark to be on the top of the results but instead it is far in a bottom and on the top, there are some random bookmarks containing letters M, A, P, S in random places.
I think that first should be the bookmarks which names exactly match the search phrase.
Then there should be bookmarks which names start with the whole search phrase.
Then there should be bookmarks which names contain the whole search phrase.
At the end should be the bookmarks which folders and name path have the letters in random places.

**Comment by chrisseroka** [comment]
Hi zbigniew, that's a really good idea. I'll try to play with that this week. Pull-requests are also most welcome.

**Comment by chrisseroka** [comment]
@zbigniew-klasik I have just published simple fix to improve sorting. It's not exactly what you described (it requires bigger refactoring) but it should solve your problem (whole phrase has bigger priority than random letters).

Can you please verify it works for you (just update extension from chrome store) ?

**Comment by zbigniew-klasik** [comment]
Yes, now it works much better, thanks :)
